### ISSUE TITLE
Transitive derive feature from tokio-postgres to postegres-types

### ISSUE THREAD

**Issue by tisonkun** [sfackler/rust-postgres#1193]
Not sure if it's desired, but now I have to specify:

```toml
tokio-postgres = { version = "0.7.12", features = ["with-jiff-0_1"] }
postgres-types = { version = "0.2.8", features = ["derive", "with-jiff-0_1"] }
```

And I wonder if it's possible to do:

```toml
tokio-postgres = { version = "0.7.12", features = ["derive", "with-jiff-0_1"] }
```
