### ISSUE TITLE
the trait `postgres::types::ToSql` is not implemented for the type `chrono::datetime::DateTime<chrono::offset::utc::UTC>`

### ISSUE THREAD

**Issue by vrcod** [sfackler/rust-postgres#127]
So I'm getting this error while trying to run a query that inserts a timestamp. I'm creating the timestamp like this:
```
let test = "2013-08-30 15:03:33";
let t = UTC.datetime_from_str(&*test, "%Y-%m-%d %H:%M:%S").unwrap();
```
but I'm getting this error:
```
error: the trait `postgres::types::ToSql` is not implemented for the type `chrono::datetime::DateTime<chrono::offset::utc::UTC>` [E0277]
```

**Comment by sfackler** [comment]
Did you enable the `chrono` Cargo feature? https://github.com/sfackler/rust-postgres#timestamptimestamptzdatetime-types

**Comment by vrcod** [comment]
@sfackler I have no idea how to enable it, I've read the documentation top to bottom. Example please?

**Comment by sfackler** [comment]
You'd change your Cargo.toml from this
```toml
[dependencies]
postgres = "0.8"
```
this this
```toml
[dependencies]
postgres = { version = "0.8", features = ["chrono"] }
```
