### ISSUE TITLE
Cannot serialize to serde_json::Value

### ISSUE THREAD

**Issue by ysimonson** [sfackler/rust-postgres#165]
Hello! I'm getting an error trying to serialize values from postgres to `serde_json::Value`:

```
src/datastore/pg.rs:97:41: 97:44 error: the trait `postgres::types::FromSql` is not implemented for the type `serde_json::value::Value` [E0277]
src/datastore/pg.rs:97 			let properties_json: JsonValue = row.get(0);
                       			                                     ^~~
src/datastore/pg.rs:97:41: 97:44 help: run `rustc --explain E0277` to see a detailed explanation
```

For reference, my `Cargo.toml` contains:

```toml
[dependencies.postgres]
version = "*"
features = ["uuid", "serde_json", "chrono"]
optional = true
```

I see the [code](https://github.com/sfackler/rust-postgres/blob/master/src/types/serde_json.rs), I have the feature enabled...what am I missing here?
