### ISSUE TITLE
Question: How to use `with-chrono` feature?

### ISSUE THREAD

**Issue by hunterlester** [sfackler/rust-postgres#211]
https://github.com/sfackler/rust-postgres#timestamptimestamptzdatetime-types

How do I implement this feature?

Does this have to do with `#![feature()]`?
Or in the features section of my Cargo.toml?

Question coming from Rust beginner,

**Comment by sfackler** [comment]
You'll enable it in your `Cargo.toml`:

```toml
[dependencies]
postgres = { version = "0.12", features = ["with-chrono"] }
```

**Comment by stuartcrobinson** [comment]
now how to use in 0.17.0 ?

https://stackoverflow.com/questions/59760741/how-to-read-postgresql-timezone-in-rust

**Comment by sfackler** [comment]
```toml
[dependencies]
postgres = { version = "0.17", features = ["with-chrono-0_4"] }
```
