### ISSUE TITLE
sha2 = "0.6.0" dependency causes "The trait `postgres::types::FromSql` is not implemented for `chrono::NaiveDateTime`"

### ISSUE THREAD

**Issue by dprien** [sfackler/rust-postgres#289]
The following project won't compile unless the sha2 dependency is removed or changed to version "0.5.3" instead (remove `Cargo.lock` & `target/` before recompiling).

Cargo.toml
```toml
[package]
name = "postgres_chrono_test"
version = "0.1.0"

[dependencies]
postgres = { version = "*", features = ["with-chrono"] }
chrono = "*"
sha2 = "0.6.0"
```

src/main.rs
```rust
extern crate chrono;
extern crate postgres;
fn main() {
    let conn = postgres::Connection::connect("postgres://test@localhost:5432", postgres::TlsMode::None).unwrap();
    for row in &conn.query("SELECT foo FROM widgets WHERE bar = 1", &[]).unwrap() {
        let _: chrono::NaiveDateTime = row.get(0);
    }
}
```

`$ cargo check`
```
error[E0277]: the trait bound `chrono::NaiveDateTime: postgres::types::FromSql` is not satisfied
 --> src/main.rs:6:44
  |
6 |         let _: chrono::NaiveDateTime = row.get(0);
  |                                            ^^^ the trait `postgres::types::FromSql` is not implemented for `chrono::NaiveDateTime`
```

I'm not sure what's going on here, if I hit a basic limitation of Rust when multiple versions of the same crate are pulled in or if this is specific to the postgres crate. Any explanation would be much appreciated.
