### ISSUE TITLE
Error retrieving column: Error(Conversion(WrongType(Type(Uuid))))

### ISSUE THREAD

**Issue by rrmdn** [sfackler/rust-postgres#407]
Hi, I am new to Rust, but I am sure there is nothing wrong with my code since it compiles.
However, I've got this error when I was trying to retrieve a UUID column type from a row:
```
thread 'tokio-runtime-worker-2' panicked at 'error retrieving column "id": Error(Conversion(WrongType(Type(Uuid))))', /Users/rrmdn/.cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.15.2/src/rows.rs:201:31
```

Error came out of this code:
```rust
let id = Uuid::new_v4();
let inserts = conn.execute("
    INSERT INTO restaurant (
        id,
        name,
        address,
        logo,
        cover,
        location_url
    ) VALUES ($1, $2, $3, $4, $5, $6)
", &[
    &id,
    &new_restaurant.name,
    &new_restaurant.address,
    &new_restaurant.logo,
    &new_restaurant.cover,
    &new_restaurant.location_url
]).unwrap();
let rows = conn.query("
    SELECT *
    FROM restaurant
    WHERE id = $1
", &[&id]).unwrap();

let row = rows.get(0);
Ok(Restaurant {
    id: row.get("id"),
    name: row.get("name"),
    address: row.get("address"),
    logo: row.get("logo"),
    cover: row.get("cover"),
    location_url: row.get("location_url"),
})
```
The error goes away if I don't try to get `id` column (`row.get("id")`).

Dependencies:
```toml
[dependencies]
hyper = "0.12"
log = "0.4"
pretty_env_logger = "0.3"
futures = "0.1.25"
juniper = "0.11"
juniper_hyper = "0.2.0"
postgres = { version = "0.15", features = ["with-uuid", "with-chrono"]}
r2d2_postgres = "0.14.0"
r2d2 = "0.8"
uuid = { version = "0.5", features = ["v4"] }
chrono = "0.4"
```
cargo 1.31.0 (339d9f9c8 2018-11-16)
rustc 1.31.1 (b6c32da9b 2018-12-18)
