### ISSUE TITLE
`postgres` does not have  `serde-json` feature

### ISSUE THREAD

**Issue by ufoscout** [sfackler/rust-postgres#416]
I need to read and write to a JSONB column, but I can't find a way to enable the serde feature.
In my Cargo.toml:
```toml
[dependencies]
postgres = { version = "0.15", features = ["serde-json", "serde", "serde_json", "serdejson"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
```

cargo build output:
```bash
the package `test_postgres` depends on `postgres`, with features: `serde-json, serde_json, serde, serdejson` but `postgres` does not have these features.
```

I tried writing it in different ways with no luck.

Would you be able to provide a complete example of an insert to and a select from a JOSNB column with serde?
