### ISSUE TITLE
`try_next` not works in `tokio-postgres` and async funtion

### ISSUE THREAD

**Issue by UkonnRa** [sfackler/rust-postgres#485]
I find that `try_next` not works in the async block?

Dependencies:
``` toml
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly", "compat"] }
[dependencies.tokio-postgres]
version = "0.4.0-rc.3"
git = "https://github.com/sfackler/rust-postgres.git"
branch = "std-futures"
features = ["with-uuid-0_7", "with-chrono-0_4", "with-serde_json-1"]
```

``` rust
    pub type Res<T> = Result<T, Box<dyn Error + Send + Sync>>;

    async fn get_by_email(client: &Client, email: &String) -> Res<Option<UserPresent>> {
        let mut trans = client.transaction().await?;
        let email_stmt = trans.prepare("SELECT id FROM users WHERE email = $1").await?;
        let email_opt = trans
            .query(&email_stmt, &[email])
            .map_ok(|row: Row| row.get::<_, String>("id"))
            .try_next()
            .await?;

        Ok(None)
    }
```

And Error got;

```
38 |           let email_opt = trans
   |  _________________________^
39 | |             .query(&email_stmt, &[email])
40 | |             .map_ok(|row: Row| row.get::<_, String>("id"))
41 | |             .try_next()
42 | |             .await?;
   | |__________________^ within `impl core::future::future::Future`, the trait `std::marker::Unpin` is not implemented for `std::future::GenFuture<[static generator@DefId(52:1191 ~ tokio_postgres[9403]::query[0]::start[0]::{{closure}}[0]) 0:std::sync::Arc<tokio_postgres::client::InnerClient>, 1:std::result::Result<std::vec::Vec<u8>, tokio_postgres::error::Error> for<'r> {std::sync::Arc<tokio_postgres::client::InnerClient>, std::result::Result<std::vec::Vec<u8>, tokio_postgres::error::Error>, std::vec::Vec<u8>, tokio_postgres::client::Responses, fn(std::result::Result<postgres_protocol::message::backend::Message, tokio_postgres::error::Error>) -> std::result::Result<<std::result::Result<postgres_protocol::message::backend::Message, tokio_postgres::error::Error> as std::ops::Try>::Ok, <std::result::Result<postgres_protocol::message::backend::Message, tokio_postgres::error::Error> as std::ops::Try>::Error> {<std::result::Result<postgres_protocol::message::backend::Message, tokio_postgres::error::Error> as std::ops::Try>::into_result}, impl core::future::future::Future, ()}]>`
```

But it works if:
``` rust
    async fn get_by_email(&mut self, email: &String) -> Res<Option<UserPresent>> {
        let mut trans = self.0.transaction().await?;
        let email_stmt = trans.prepare("SELECT id FROM users WHERE email = $1").await?;
        let email_opt: Vec<String> = trans // The error here will disappear
            .query(&email_stmt, &[email])
            .map_ok(|row: Row| row.get::<_, String>("id"))
            .try_collect()
            .await?;

        Ok(None)
    }
```
