### ISSUE TITLE
Postgres Uuid version problem

### ISSUE THREAD

**Issue by Ked57** [sfackler/rust-postgres#507]
Hello, I'm building a graphql API that uses postgres and Juniper. My problem is that postgres require a certain version of the uuid crate (I think it's 5.0.0) and Juniper requires a higher version (latest works fine) so I'm kind of having a problem here. What can I do ?

**Comment by sfackler** [comment]
Newer versions of the postgres crate support newer versions of UUID.

**Comment by Ked57** [comment]
Well I've got 
```
juniper = "0.14.1"
uuid = { version = "0.8.1" , features = ["v4"] }
r2d2_postgres = "0.14.0"
r2d2 = "0.8.6"
postgres = { version = "0.15.2", features = ["with-uuid"] }
```
Latest versions for all of these crates, and I still get an error when trying to do something like `row.get(0)`
I'm probably missing something but i don't know what

**Comment by sfackler** [comment]
The latest version of the postgres crate is 0.17.0-alpha.1

**Comment by sfackler** [comment]
You can alternatively convert the UUID to some other form like a string in Postgres, or make a wrapper type that implements ToSql and FromSql.

**Comment by Ked57** [comment]
well if I put `postgres = { version = "0.17.0-alpha.1", features = ["with-uuid"] }` I get 
```
failed to select a version for `postgres`.
    ... required by package `iq-api v0.1.0 (/home/ked/Documents/dev/instaq/rust-api)`
versions that meet the requirements `^0.17.0-alpha.1` are: 0.17.0-alpha.1

the package `iq-api` depends on `postgres`, with features: `with-uuid` but `postgres` does not have these features.


failed to select a version for `postgres` which could resolve this conflict
```

**Comment by Ked57** [comment]
Can I have some help with this please ? I don't understand how I'm supposed to use the alpha if cargo can't find it

**Comment by dutchmartin** [comment]
> well if I put `postgres = { version = "0.17.0-alpha.1", features = ["with-uuid"] }` I get
> 
> ```
> failed to select a version for `postgres`.
>     ... required by package `iq-api v0.1.0 (/home/ked/Documents/dev/instaq/rust-api)`
> versions that meet the requirements `^0.17.0-alpha.1` are: 0.17.0-alpha.1
> 
> the package `iq-api` depends on `postgres`, with features: `with-uuid` but `postgres` does not have these features.
> 
> 
> failed to select a version for `postgres` which could resolve this conflict
> ```
> 
> Cargo can't seem to find the latest alpha

The postgres crate feature gates several versions of uuid.
Take a look at the cargo.toml:
```toml
[features]
default = ["runtime"]
runtime = ["tokio-postgres/runtime", "tokio", "lazy_static", "log"]

with-bit-vec-0_6 = ["tokio-postgres/with-bit-vec-0_6"]
with-chrono-0_4 = ["tokio-postgres/with-chrono-0_4"]
with-eui48-0_4 = ["tokio-postgres/with-eui48-0_4"]
with-geo-types-0_4 = ["tokio-postgres/with-geo-types-0_4"]
with-serde_json-1 = ["tokio-postgres/with-serde_json-1"]
with-uuid-0_7 = ["tokio-postgres/with-uuid-0_7"]
with-uuid-0_8 = ["tokio-postgres/with-uuid-0_8"]
```

Cargo can not resolve your feature since the feature 'with-uuid' does not exits.
but you need the feature 'with-uuid-0_8', since you need the 0.8 version of uuid.
Like this:
`postgres = { version = "0.17.0-alpha.1", features = ["with-uuid-0_8"] }`
