### ISSUE TITLE
error: the trait bound `tokio_postgres::NoTls: bb8_postgres::tokio_postgres::tls::MakeTlsConnect<bb8_postgres::tokio_postgres::Socket>` is not satisfied

### ISSUE THREAD

**Issue by kushwahashiv** [sfackler/rust-postgres#553]
```toml
[package]
name = "db_pool"
version = "0.1.0"
edition = "2018"

[dependencies]
bb8 = "0.3.1"
bb8-postgres = "0.3.1"
diesel = { version = "1.4.3", features = ["postgres", "extras"] }
failure = "0.1"
futures = "0.1"
futures-state-stream = "0.2"
postgres = "0.17.0"
tokio-postgres = "0.5.1"
```

```rust 
use bb8;
use bb8_postgres;
use futures::future;
use futures::prelude::*;
use tokio_postgres;
use tokio_postgres::NoTls;


#[derive(Clone, Debug)]
pub struct Pool {
    inner: bb8::Pool<bb8_postgres::PostgresConnectionManager<NoTls>>
}

impl From<bb8::Pool<bb8_postgres::PostgresConnectionManager<NoTls>>> for Pool {
    fn from(v: bb8::Pool<bb8_postgres::PostgresConnectionManager<NoTls>>) -> Self {
        Self { inner: v }
    }
}

```

I am getting following error:

```cmd
error: the trait bound `tokio_postgres::NoTls: bb8_postgres::tokio_postgres::tls::MakeTlsConnect<bb8_postgres::tokio_postgres::Socket>` is not satisfied
label: the trait `bb8_postgres::tokio_postgres::tls::MakeTlsConnect<bb8_postgres::tokio_postgres::Socket>` is not implemented for `tokio_postgres::NoTls`
```

![image](https://user-images.githubusercontent.com/4386810/72470628-e7fd1880-3795-11ea-8d4b-284585d2a14e.png)

What I'm missing here.

/Shiv
