### ISSUE TITLE
With actix-web 3, any version of tokio-postgress >0.5.5 fails with something like: "not running under tokio v1" error

### ISSUE THREAD

**Issue by arekbal** [sfackler/rust-postgres#744]
Just like in the title:
With actix-web 3, any version of tokio-postgress >0.5.5 fails with something like: "not running under tokio v1" error.

working deps:
```toml
actix-web = "3.3.2"
paperclip = { git = "https://github.com/wafflespeanut/paperclip.git", features = ["actix", "uuid", "chrono"] }
futures = "0.3.13"
serde = { version = "1.0.124", features = ["derive"] }
dotenv = "0.15.0"
config = "0.10.1"
tokio-postgres = { version="0.5.5", features=["with-uuid-0_8", "with-serde_json-1", "with-chrono-0_4"] }
deadpool-postgres = "0.5.6"
slog = "2.7.0"
slog-term = "2.8.0"
slog-async = "2.6.0"
slog-envlogger = "2.2.0"
actix-cors = "0.5.4"
uuid = { version="0.8.2", default-features = false, features = ["serde", "v4"] }
chrono = { version="0.4.19", features = ["serde"] } 

[dev-dependencies]
lazy_static = "1.4.0"
serde_json = "1.0.48"
```

switching deadpool or tokio up leads to every requiest involving db erroring/panicking with something along 'not running under tokio v1'. Depending on the version the message changes a bit, but means the same, tokio's context.current() errs out.
